<?php

/*
 * This file is part of the BootstrapCheckboxBundle.
 *
 * (c) Janusz Paszyński <https://github.com/Eloar>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace ITChaos\Bundle\BootstrapCheckboxBundle\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;

/**
 * Type for field using bootstrap-checkbox
 * @package ITChaos\Bundle\BootstrapCheckboxBundle\Form
 */
class BootstrapCheckboxType extends AbstractType
{
    /** {@inheritdoc} */
    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        // todo: implement
        parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
    }

    /** {@inheritdoc} */
    public function getName()
    {
        return 'bootstrap-checkbox';
    }

    /** {@inheritdoc} */
    public function getParent()
    {
        return 'checkbox';
    }
}
